CC=gcc -Wall

EX1 = hierarquia
EX2 = exec
EX3 = busca_vetor

PROGS = $(EX1) $(EX2) $(EX3)

all: $(PROGS)

$(EX1): $(EX1).c
	$(CC) $(EX1).c -o $(EX1).out

$(EX2): $(EX2).c
	$(CC) $(EX2).c -o $(EX2).out

$(EX3): $(EX3).c
	$(CC) $(EX3).c -o $(EX3).out
