CC=gcc -Wall                               
                                           
EX0 = busca                           
                                           
PROGS = $(EX0)
                                           
all: $(PROGS)                              
                                           
$(EX0): $(EX0).c                           
	$(CC) $(EX0).c -o $(EX0).out             

